# Usamos la imagen oficial de Playwright de Microsoft que ya trae Node.js y los navegadores instalados
image: mcr.microsoft.com/playwright:v1.42.0-jammy

stages:
  - test

playwright_tests:
  stage: test
  script:
    - npm ci
    - npx playwright install --with-deps
    - npx playwright test
  # Esta sección guarda tu reporte HTML igual que en GitHub
  artifacts:
    when: always
    paths:
      - playwright-report/
    expire_in: 30 days