import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://erpperu2-crt.smartclic.pe/home');
  await page.getByText('Productos y servicios').click();
  await page.locator('[id="nvg_selects_cmp-header-selects_select:select-module-203-item-2007"]').click();
  await page.getByText('Crear ítems', { exact: true }).click();
  await page.locator('[id="lgt_cmp-items_cmp-datos-items.cmp-option-button:crear"]').click();
  await page.locator('[id="lgt_cmp-items_cmp-datos-items.cmp-option-button:crear"]').click();
  await page.getByText('PNuevo producto').click();
  await page.locator('div').filter({ hasText: /^Opciones avanzadas \(opcional\)$/ }).click();
  await page.getByRole('textbox', { name: 'Ej. Gaseosa Kola R (500ml)' }).click();
  await page.getByRole('textbox', { name: 'Ej. Gaseosa Kola R (500ml)' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Ej. Gaseosa Kola R (500ml)' }).fill('I');
  await page.getByRole('textbox', { name: 'Ej. Gaseosa Kola R (500ml)' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Ej. Gaseosa Kola R (500ml)' }).fill('Item estricto gravado con equilavente');
  await page.getByRole('textbox', { name: 'Monto final' }).click();
  await page.getByRole('textbox', { name: 'Monto final' }).fill('12');
  await page.locator('[id="lgt_cmp-registro-item_cmp-body-item_cmp-tabs-item.v-tabs:tabs-1"]').nth(1).click();
  await page.locator('[id="lgt_reg-item_v-tab:stock-almacen_cmp-card-stock:control-estricto"]').click();
  await page.locator('[id="lgt_cmp-card-almacen_v-step:cantidad"]').first().click();
  await page.locator('[id="lgt_cmp-card-almacen_v-step:cantidad"]').first().fill('100');
  await page.locator('[id="lgt_cmp-card-almacen_v-step:cantidad"]').nth(1).click();
  await page.locator('[id="lgt_cmp-card-almacen_v-step:cantidad"]').nth(1).fill('100');
  await page.getByText('(Opcional)').nth(2).click();
  await page.locator('[id="lgt_cmp-registro-item_cmp-body-item_cmp-tabs-item.v-tabs:tabs-4"]').nth(3).click();
  await page.getByText('AQUÍ').click();
  await page.getByRole('textbox', { name: 'Digita el nombre de la' }).click();
  await page.getByRole('textbox', { name: 'Digita el nombre de la' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Digita el nombre de la' }).fill('E');
  await page.getByRole('textbox', { name: 'Digita el nombre de la' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Digita el nombre de la' }).fill('Equivalente ');
  await page.getByRole('textbox', { name: 'Digita el nombre de la' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Digita el nombre de la' }).fill('Equivalente X2');
  await page.getByRole('textbox', { name: 'Digita el nombre de la' }).press('CapsLock');
  await page.locator('div').filter({ hasText: /^Seleccionar$/ }).nth(2).click();
  await page.locator('div').filter({ hasText: /^Gravado \(Paga IGV 18%\)$/ }).first().click();
  await page.locator('[id="lgt_reg-item_v-drape:gestion-equivalencia_v-step:cantidad_div:increase"]').click();
  await page.locator('[id="lgt_reg-item_v-drape:gestion-equivalencia_v-step:cantidad_div:increase"]').click();
  await page.getByRole('textbox', { name: 'precio base' }).click();
  await page.getByRole('textbox', { name: 'precio base' }).fill('11');
  await page.getByRole('button', { name: 'Crear Equivalencia' }).click();
  await page.getByRole('button', { name: 'Agregar equivalencia' }).click();
  await page.getByRole('textbox', { name: 'Digita el nombre de la' }).click();
  await page.getByRole('textbox', { name: 'Digita el nombre de la' }).fill('equivalente ');
  await page.getByRole('textbox', { name: 'Digita el nombre de la' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Digita el nombre de la' }).fill('equivalente C3');
  await page.getByRole('textbox', { name: 'Digita el nombre de la' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Digita el nombre de la' }).fill('equivalente ');
  await page.getByRole('textbox', { name: 'Digita el nombre de la' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Digita el nombre de la' }).fill('equivalente X');
  await page.getByRole('textbox', { name: 'Digita el nombre de la' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Digita el nombre de la' }).fill('equivalente X3');
  await page.locator('div').filter({ hasText: /^Seleccionar$/ }).nth(2).click();
  await page.locator('div').filter({ hasText: /^Gravado \(Paga IGV 18%\)$/ }).first().click();
  await page.locator('[id="lgt_reg-item_v-drape:gestion-equivalencia_v-step:cantidad_div:increase"]').click();
  await page.locator('[id="lgt_reg-item_v-drape:gestion-equivalencia_v-step:cantidad_div:increase"]').click();
  await page.locator('[id="lgt_reg-item_v-drape:gestion-equivalencia_v-step:cantidad_div:increase"]').click();
  await page.getByRole('textbox', { name: 'precio base' }).click();
  await page.getByRole('textbox', { name: 'Monto final' }).click();
  await page.getByRole('textbox', { name: 'Monto final' }).fill('10');
  await page.getByRole('button', { name: 'Crear Equivalencia' }).click();
  await page.locator('[id="lgt_cmp-registro-item_cmp-body-item_cmp-tabs-item.v-tabs:tabs-4"]').nth(4).click();
  await page.locator('div').filter({ hasText: /^Selectores\(Opcional\)$/ }).first().click();
  await page.getByRole('button', { name: 'Crear producto' }).click();
  await page.getByRole('button', { name: 'Ir a lista de ítems' }).click();
  await page.locator('.flex-row-align-items-center-justify-content-center > .cmp-dropdown > .cmp-dropdown-toggle').first().click();
  await page.locator('[id="lgt_movimientos_cmp-grid-options:opciones_movimiento_cmp-dropdown:options-li:ver-item"]').click();
  await page.locator('[id="lgt_ver-item_cmp-dashboard-item:tabs:cmp-tabs-options-item:opcion_div:ventas"]').click();
  await page.locator('[id="lgt_ver-item_cmp-dashboard-item:tabs:cmp-tabs-options-item:opcion_div:compras"]').click();
  await page.locator('[id="lgt_ver-item_cmp-dashboard-item:tabs:cmp-tabs-options-item:opcion_div:bitacora"]').click();
  await page.getByRole('button', { name: 'Atrás' }).click();
});