import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  //Creacion de Servicios:

  await page.locator('[id="lgt_cmp-items_cmp-datos-items.cmp-option-button:crear"]').click();
  await page.getByText('SNuevo servicio').click();
  await page.locator('div').filter({ hasText: /^Opciones avanzadas \(opcional\)$/ }).click();
  await page.getByRole('textbox', { name: 'Ej. Gaseosa Kola R (500ml)' }).click();
  await page.getByRole('textbox', { name: 'Ej. Gaseosa Kola R (500ml)' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Ej. Gaseosa Kola R (500ml)' }).fill('I');
  await page.getByRole('textbox', { name: 'Ej. Gaseosa Kola R (500ml)' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Ej. Gaseosa Kola R (500ml)' }).fill('Item servicio gravado');
  await page.getByRole('textbox', { name: 'Monto final' }).first().click();
  await page.getByRole('textbox', { name: 'Monto final' }).first().fill('1001');
  await page.getByRole('textbox', { name: 'Monto final' }).nth(1).click();
  await page.getByRole('textbox', { name: 'Monto final' }).first().fill('10010');
  await page.getByRole('textbox', { name: 'Monto final' }).nth(1).fill('00');
  await page.getByRole('textbox', { name: 'Monto final' }).first().click();
  await page.getByRole('textbox', { name: 'Monto final' }).first().fill('10');
  await page.getByRole('textbox', { name: 'Monto final' }).nth(1).click();
  await page.getByRole('textbox', { name: 'Monto final' }).nth(1).fill('10');
  await page.locator('[id="lgt_cmp-registro-item_cmp-body-item_cmp-tabs-item.v-tabs:tabs-1"]').nth(1).click();
  await page.locator('div').filter({ hasText: /^REGRESION$/ }).nth(2).click();
  await page.locator('div').filter({ hasText: /^REGRESION$/ }).nth(4).click();
  await page.locator('div').filter({ hasText: /^Ninguna$/ }).nth(2).click();
  await page.getByText('AUTO-TEST').click();
  await page.locator('div').filter({ hasText: /^Ninguna$/ }).nth(2).click();
  await page.getByText('AUTOMATIZADO').click();
  await page.getByRole('textbox', { name: 'Descripción del ítem' }).click();
  await page.getByRole('textbox', { name: 'Descripción del ítem' }).fill('nuevo item desdes auto');
  await page.locator('[id="lgt_cmp-registro-item_cmp-body-item_cmp-tabs-item.v-tabs:tabs-3"]').nth(2).click();
  await page.locator('[id="lgt_reg-item_v-tab:campos-adicionales_grilla-campos-adicionales:campo-adicional_v-input:texto"]').click();
  await page.locator('[id="lgt_reg-item_v-tab:campos-adicionales_grilla-campos-adicionales:campo-adicional_v-input:texto"]').fill('nuevo servicio');
  await page.locator('[id="lgt_reg-item_v-tab:campos-adicionales_grilla-campos-adicionales:campo-adicional_v-input:fecha"]').click();
  await page.getByRole('button', { name: 'miércoles, 8 de abr de' }).click();
  await page.locator('[id="lgt_reg-item_v-tab:campos-adicionales_grilla-campos-adicionales:campo-adicional_v-input:numerico"]').click();
  await page.locator('[id="lgt_reg-item_v-tab:campos-adicionales_grilla-campos-adicionales:campo-adicional_v-input:numerico"]').fill('122222');
  await page.getByRole('button', { name: 'Crear servicio' }).click();
  await page.getByRole('button', { name: 'Ir a lista de ítems' }).click();
  await page.locator('.flex-row-align-items-center-justify-content-center > .cmp-dropdown > .cmp-dropdown-toggle').first().click();
  await page.locator('[id="lgt_movimientos_cmp-grid-options:opciones_movimiento_cmp-dropdown:options-li:ver-item"]').click();
  await page.locator('[id="lgt_ver-item_cmp-dashboard-item:tabs:cmp-tabs-options-item:opcion_div:bitacora"]').click();
  await page.getByRole('button', { name: 'Atrás' }).click();


  //Creacion de servicio inafecto


  await page.locator('[id="lgt_cmp-items_cmp-datos-items.cmp-option-button:crear"]').click();
  await page.getByText('SNuevo servicio').click();
  await page.getByRole('textbox', { name: 'Ej. Gaseosa Kola R (500ml)' }).click();
  await page.getByRole('textbox', { name: 'Ej. Gaseosa Kola R (500ml)' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Ej. Gaseosa Kola R (500ml)' }).fill('S');
  await page.getByRole('textbox', { name: 'Ej. Gaseosa Kola R (500ml)' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Ej. Gaseosa Kola R (500ml)' }).fill('Servicio inafecto');
  await page.locator('div').filter({ hasText: /^Gravado \(Paga IGV 18%\)$/ }).nth(2).click();
  await page.locator('div').filter({ hasText: /^Inafecto \(No paga IGV\)$/ }).click();
  await page.getByRole('textbox', { name: 'Monto final' }).first().click();
  await page.getByRole('textbox', { name: 'Monto final' }).first().fill('10');
  await page.getByRole('textbox', { name: 'Monto final' }).nth(1).click();
  await page.getByRole('textbox', { name: 'Monto final' }).nth(1).fill('10');
  await page.locator('div').filter({ hasText: /^Opciones avanzadas \(opcional\)$/ }).click();
  await page.getByText('Información adicional(').click();
  await page.locator('div').filter({ hasText: /^REGRESION$/ }).nth(2).click();
  await page.locator('div').filter({ hasText: /^REGRESION$/ }).nth(4).click();
  await page.locator('div').filter({ hasText: /^Ninguna$/ }).nth(2).click();
  await page.locator('div').filter({ hasText: /^AUTO-TEST$/ }).nth(2).click();
  await page.locator('div:nth-child(3) > .form-control > .v-select > .v-select-form > .v-select-base > .v-select-base-header > .v-select-header-base-form > .v-select-header-form > .v-select-header-form-arrow').click();
  await page.getByText('AUTOMATIZADO').click();
  await page.getByRole('textbox', { name: 'Descripción del ítem' }).click();
  await page.getByRole('textbox', { name: 'Descripción del ítem' }).fill('nuevo item desde auto');
  await page.locator('[id="lgt_cmp-registro-item_cmp-body-item_cmp-tabs-item.v-tabs:tabs-3"]').nth(2).click();
  await page.getByRole('button', { name: 'Crear servicio' }).click();
  await page.getByRole('button', { name: 'Ir a lista de ítems' }).click();
  await page.locator('.flex-row-align-items-center-justify-content-center > .cmp-dropdown > .cmp-dropdown-toggle').first().click();
  await page.locator('[id="lgt_movimientos_cmp-grid-options:opciones_movimiento_cmp-dropdown:options-li:ver-item"]').click();
  await page.locator('[id="lgt_ver-item_cmp-dashboard-item:tabs:cmp-tabs-options-item:opcion_div:bitacora"]').click();
  await page.locator('[id="lgt_ver-item_cmp-dashboard-item:tabs:cmp-tabs-options-item:opcion_div:ventas"]').click();
  await page.getByRole('button', { name: 'Atrás' }).click();


  // Creacion de insumos sin control de stock:

  await page.locator('[id="lgt_cmp-items_cmp-datos-items.cmp-option-button:crear"]').click();
  await page.getByText('INuevo insumo').click();
  await page.getByRole('textbox', { name: 'Ej. Gaseosa Kola R (500ml)' }).click();
  await page.getByRole('textbox', { name: 'Ej. Gaseosa Kola R (500ml)' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Ej. Gaseosa Kola R (500ml)' }).fill('N');
  await page.getByRole('textbox', { name: 'Ej. Gaseosa Kola R (500ml)' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Ej. Gaseosa Kola R (500ml)' }).fill('Nuevo insumo ');
  await page.locator('div').filter({ hasText: /^Opciones avanzadas \(opcional\)$/ }).click();
  await page.locator('[id="_div:dropdown"]').click();
  await page.getByText('Manual').click();
  await page.locator('[id="lgt_reg-item_v-tab:informacion-basica_v-input:codigo"]').click();
  await page.locator('[id="lgt_reg-item_v-tab:informacion-basica_v-input:codigo"]').fill('1000');
  await page.locator('[id="_div:dropdown"]').click();
  await page.getByText('Automático').click();
  await page.locator('[id="lgt_cmp-registro-item_cmp-body-item_cmp-tabs-item.v-tabs:tabs-1"]').nth(1).click();
  await page.locator('[id="lgt_reg-item_v-tab:stock-almacen_cmp-card-stock:sin-control-stock"]').click();
  await page.locator('[id="lgt_cmp-registro-item_cmp-body-item_cmp-tabs-item.v-tabs:tabs-2"]').nth(2).click();
  await page.locator('div').filter({ hasText: /^REGRESION$/ }).nth(2).click();
  await page.getByText('REGRESION').nth(1).click();
  await page.locator('div:nth-child(2) > .form-control > .v-select > .v-select-form > .v-select-base > .v-select-base-header > .v-select-header-base-form > .v-select-header-form > .v-select-header-form-arrow').first().click();
  await page.getByText('AUTO-TEST').click();
  await page.locator('div').filter({ hasText: /^Ninguna$/ }).nth(2).click();
  await page.getByText('AUTOMATIZADO').click();
  await page.locator('div').filter({ hasText: /^AUTOMATIZADO$/ }).nth(2).click();
  await page.locator('[id="lgt_cmp-registro-item_cmp-body-item_cmp-tabs-item.v-tabs:tabs-3"]').nth(3).click();
  await page.locator('[id="lgt_cmp-registro-item_cmp-body-item_cmp-tabs-item.v-tabs:tabs-4"]').nth(4).click();
  await page.getByRole('button', { name: 'Crear insumo' }).click();
  await page.getByRole('button', { name: 'Ir a lista de ítems' }).click();

  // Creacion de insumos con control de stock estricto:

  await page.locator('[id="lgt_cmp-items_cmp-datos-items.cmp-option-button:crear"]').click();
  await page.getByText('INuevo insumo').click();
  await page.getByRole('textbox', { name: 'Ej. Gaseosa Kola R (500ml)' }).click();
  await page.getByRole('textbox', { name: 'Ej. Gaseosa Kola R (500ml)' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Ej. Gaseosa Kola R (500ml)' }).fill('N');
  await page.getByRole('textbox', { name: 'Ej. Gaseosa Kola R (500ml)' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Ej. Gaseosa Kola R (500ml)' }).fill('Nuevo insumo test1');
  await page.locator('div').filter({ hasText: /^Opciones avanzadas \(opcional\)$/ }).click();
  await page.locator('[id="lgt_cmp-registro-item_cmp-body-item_cmp-tabs-item.v-tabs:tabs-1"]').nth(1).click();
  await page.locator('[id="lgt_reg-item_v-tab:stock-almacen_cmp-card-stock:control-estricto"]').click();
  await page.locator('[id="lgt_cmp-card-almacen_v-step:cantidad"]').first().click();
  await page.locator('[id="lgt_cmp-card-almacen_v-step:cantidad"]').first().fill('100');
  await page.locator('[id="lgt_cmp-card-almacen_v-step:cantidad"]').nth(1).click();
  await page.locator('[id="lgt_cmp-card-almacen_v-step:cantidad"]').nth(1).fill('100');
  await page.locator('[id="lgt_cmp-registro-item_cmp-body-item_cmp-tabs-item.v-tabs:tabs-2"]').nth(2).click();
  await page.locator('div').filter({ hasText: /^REGRESION$/ }).nth(2).click();
  await page.locator('div').filter({ hasText: /^REGRESION$/ }).nth(4).click();
  await page.locator('div').filter({ hasText: /^Ninguna$/ }).nth(2).click();
  await page.getByText('AUTO-TEST').click();
  await page.locator('div:nth-child(3) > .form-control > .v-select > .v-select-form > .v-select-base > .v-select-base-header > .v-select-header-base-form > .v-select-header-form > .v-select-header-form-arrow').click();
  await page.getByText('AUTOMATIZADO').click();
  await page.getByRole('textbox', { name: 'Descripción del ítem' }).click();
  await page.locator('[id="lgt_cmp-registro-item_cmp-body-item_cmp-tabs-item.v-tabs:tabs-3"]').nth(3).click();
  await page.getByText('Campos adicionales(Opcional)').click();
  await page.locator('[id="lgt_reg-item_v-tab:campos-adicionales_grilla-campos-adicionales:campo-adicional_v-input:texto"]').click();
  await page.locator('[id="lgt_reg-item_v-tab:campos-adicionales_grilla-campos-adicionales:campo-adicional_v-input:texto"]').fill('nuevo insumo desde auto');
  await page.locator('div').filter({ hasText: /^crt$/ }).nth(2).click();
  await page.getByText('crt').nth(1).click();
  await page.locator('[id="lgt_reg-item_v-tab:campos-adicionales_grilla-campos-adicionales:campo-adicional_v-input:fecha"]').click();
  await page.getByRole('button', { name: 'jueves, 30 de abr de' }).click();
  await page.locator('[id="lgt_reg-item_v-tab:campos-adicionales_grilla-campos-adicionales:campo-adicional_v-input:numerico"]').click();
  await page.locator('[id="lgt_reg-item_v-tab:campos-adicionales_grilla-campos-adicionales:campo-adicional_v-input:numerico"]').fill('12121');
  await page.getByRole('button', { name: 'Crear insumo' }).click();
 
  await page.getByRole('button', { name: 'Ir a lista de ítems' }).click();
  await page.locator('.v-icon-base > .icon').first().click();
  await page.locator('[id="lgt_items_cmp-grid-item-option:opciones_items_cmp-dropdown:options-li:visualizar-item"]').click();
  await page.locator('.v-modal > div').first().click();
  await page.locator('.flex-row-align-items-center-justify-content-center > .cmp-dropdown > .cmp-dropdown-toggle').first().click();
  await page.locator('[id="lgt_movimientos_cmp-grid-options:opciones_movimiento_cmp-dropdown:options-li:ver-item"]').click();
  await page.locator('[id="lgt_ver-item_cmp-dashboard-item:tabs:cmp-tabs-options-item:opcion_div:compras"]').click();
  await page.locator('[id="lgt_ver-item_cmp-dashboard-item:tabs:cmp-tabs-options-item:opcion_div:bitacora"]').click();
  await page.getByRole('button', { name: 'Atrás' }).click();
  await page.getByRole('button', { name: 'Ir a lista de ítems' }).click();
  await page.locator('.v-icon-base > .icon').first().click();
  await page.locator('[id="lgt_items_cmp-grid-item-option:opciones_items_cmp-dropdown:options-li:visualizar-item"]').click();
  await page.locator('.v-modal > div').first().click();
  await page.locator('.flex-row-align-items-center-justify-content-center > .cmp-dropdown > .cmp-dropdown-toggle').first().click();
  await page.locator('[id="lgt_movimientos_cmp-grid-options:opciones_movimiento_cmp-dropdown:options-li:ver-item"]').click();
  await page.locator('[id="lgt_ver-item_cmp-dashboard-item:tabs:cmp-tabs-options-item:opcion_div:compras"]').click();
  await page.locator('[id="lgt_ver-item_cmp-dashboard-item:tabs:cmp-tabs-options-item:opcion_div:bitacora"]').click();
  await page.getByRole('button', { name: 'Atrás' }).click();


  //Creacion de insumo con control de stock estricto y equivalencias:

  await page.locator('[id="lgt_cmp-items_cmp-datos-items.cmp-option-button:crear"]').click();
  await page.getByText('INuevo insumo').click();
  await page.getByRole('textbox', { name: 'Ej. Gaseosa Kola R (500ml)' }).click();
  await page.getByRole('textbox', { name: 'Ej. Gaseosa Kola R (500ml)' }).fill('nuevo insumo tessss');
  await page.locator('div').filter({ hasText: /^Opciones avanzadas \(opcional\)$/ }).click();
  await page.locator('[id="lgt_cmp-registro-item_cmp-body-item_cmp-tabs-item.v-tabs:tabs-1"]').nth(1).click();
  await page.locator('[id="lgt_reg-item_v-tab:stock-almacen_cmp-card-stock:control-estricto"]').click();
  await page.locator('[id="lgt_cmp-card-almacen_v-step:cantidad"]').first().click();
  await page.locator('[id="lgt_cmp-card-almacen_v-step:cantidad"]').first().fill('100');
  await page.locator('[id="lgt_cmp-card-almacen_v-step:cantidad"]').nth(1).click();
  await page.locator('[id="lgt_cmp-card-almacen_v-step:cantidad"]').nth(1).fill('100');
  await page.locator('[id="lgt_cmp-registro-item_cmp-body-item_cmp-tabs-item.v-tabs:tabs-2"]').nth(2).click();
  await page.locator('div').filter({ hasText: /^REGRESION$/ }).nth(2).click();
  await page.getByText('REGRESION').nth(1).click();
  await page.locator('div').filter({ hasText: /^Ninguna$/ }).nth(2).click();
  await page.getByText('AUTO-TEST').click();
  await page.locator('div').filter({ hasText: /^Ninguna$/ }).nth(2).click();
  await page.getByText('AUTOMATIZADO').click();
  await page.locator('[id="lgt_cmp-registro-item_cmp-body-item_cmp-tabs-item.v-tabs:tabs-3"]').nth(3).click();
  await page.getByText('AQUÍ').click();
  await page.getByRole('textbox', { name: 'Digita el nombre de la' }).click();
  await page.getByRole('textbox', { name: 'Digita el nombre de la' }).fill('equivalente');
  await page.getByRole('textbox', { name: 'Digita el nombre de la' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Digita el nombre de la' }).fill('equivalenteX2');
  await page.getByRole('textbox', { name: 'Digita el nombre de la' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Digita el nombre de la' }).fill('equivalenteX2 insumo');
  await page.locator('[id="lgt_reg-item_v-drape:gestion-equivalencia_v-step:cantidad_div:increase"]').click();
  await page.locator('[id="lgt_reg-item_v-drape:gestion-equivalencia_v-step:cantidad_div:increase"]').click();
  await page.getByRole('button', { name: 'Crear Equivalencia' }).click();
  await page.getByRole('button', { name: 'Crear insumo' }).click();
  await page.getByRole('button', { name: 'Ir a lista de ítems' }).click();
  await page.getByText('IeInsumo').click();
  await page.locator('.flex-row-align-items-center-justify-content-center > .cmp-dropdown > .cmp-dropdown-toggle').first().click();
  await page.locator('[id="lgt_items_cmp-grid-item-option:opciones_items_cmp-dropdown:options-li:visualizar-item"]').click();
  await page.locator('.v-modal > div').first().click();
  await page.locator('.flex-row-align-items-center-justify-content-center > .cmp-dropdown > .cmp-dropdown-toggle').first().click();
  await page.locator('[id="lgt_movimientos_cmp-grid-options:opciones_movimiento_cmp-dropdown:options-li:ver-item"]').click();
  await page.getByText('Compras', { exact: true }).click();
  await page.getByText('Bitácora').click();
  await page.getByRole('button', { name: 'Atrás' }).click();

  //Creacio de insumo con control de stock flexible:

  await page.locator('[id="lgt_cmp-items_cmp-datos-items.cmp-option-button:crear"]').click();
  await page.getByText('INuevo insumo').click();
  await page.getByRole('textbox', { name: 'Ej. Gaseosa Kola R (500ml)' }).click();
  await page.getByRole('textbox', { name: 'Ej. Gaseosa Kola R (500ml)' }).fill('nuevo insumo tetesss');
  await page.locator('div').filter({ hasText: /^Opciones avanzadas \(opcional\)$/ }).click();
  await page.locator('[id="lgt_cmp-registro-item_cmp-body-item_cmp-tabs-item.v-tabs:tabs-1"]').nth(1).click();
  await page.locator('[id="lgt_reg-item_v-tab:stock-almacen_cmp-card-stock:control-flexible"]').click();
  await page.locator('[id="lgt_cmp-card-almacen_v-step:cantidad"]').first().click();
  await page.locator('[id="lgt_cmp-card-almacen_v-step:cantidad"]').first().fill('100');
  await page.locator('[id="lgt_cmp-card-almacen_v-step:cantidad"]').nth(1).click();
  await page.locator('[id="lgt_cmp-card-almacen_v-step:cantidad"]').nth(1).fill('100');
  await page.locator('[id="lgt_cmp-registro-item_cmp-body-item_cmp-tabs-item.v-tabs:tabs-2"]').nth(2).click();
  await page.getByRole('button', { name: 'Crear insumo' }).click();
  await page.getByRole('button', { name: 'Ir a lista de ítems' }).click();
 
  //Creacion de combo con items normales

  await page.locator('[id="lgt_cmp-items_cmp-datos-items.cmp-option-button:crear"]').click();
  await page.getByText('CNuevo combo').click();
  await page.getByRole('textbox', { name: 'Ej. Gaseosa Kola R (500ml)' }).click();
  await page.getByRole('textbox', { name: 'Ej. Gaseosa Kola R (500ml)' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Ej. Gaseosa Kola R (500ml)' }).fill('NU');
  await page.getByRole('textbox', { name: 'Ej. Gaseosa Kola R (500ml)' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Ej. Gaseosa Kola R (500ml)' }).fill('Nuevo combo con items estricto y flexible');
  await page.getByRole('textbox', { name: 'Monto final' }).first().click();
  await page.getByRole('textbox', { name: 'Monto final' }).first().fill('5050');
  await page.locator('.content.has-options > .options-final > .valor-final > .v-input > .v-input-form > .v-input-form-base > .v-input-form-base-container').click();
  await page.getByRole('textbox', { name: 'Monto final' }).nth(1).fill('');
  await page.getByRole('textbox', { name: 'Monto final' }).first().click();
  await page.getByRole('textbox', { name: 'Monto final' }).first().fill('50');
  await page.getByText('Precio dolares$18%Afectación').click();
  await page.getByRole('textbox', { name: 'Monto final' }).nth(1).click();
  await page.getByRole('textbox', { name: 'Monto final' }).nth(1).fill('10');
  await page.locator('[id="lgt_cmp-registro-item_cmp-body-item_cmp-tabs-item.v-tabs:tabs-1"]').nth(1).click();
  await page.getByRole('textbox', { name: 'Buscar nombre del producto, c' }).click();
  await page.getByRole('textbox', { name: 'Buscar nombre del producto, c' }).fill('111111');
  await page.getByText('Pproducto111111Item para combos estricto gravado0 un').click();
  await page.getByRole('textbox', { name: 'Buscar nombre del producto, c' }).click();
  await page.getByRole('textbox', { name: 'Buscar nombre del producto, c' }).fill('121212');
  await page.getByText('item para combos gravado').click();
  await page.locator('div').filter({ hasText: /^Opciones avanzadas \(opcional\)$/ }).click();
  await page.locator('[id="lgt_cmp-registro-item_cmp-body-item_cmp-tabs-item.v-tabs:tabs-1"]').nth(2).click();
  await page.locator('.subcategoria > .form-control > .v-select > .v-select-form > .v-select-base > .v-select-base-header > .v-select-header-base-form > .v-select-header-form > .v-select-header-form-arrow').first().click();
  await page.getByText('AUTO-TEST').click();
  await page.locator('div:nth-child(2) > .form-control > .v-select > .v-select-form > .v-select-base > .v-select-base-header > .v-select-header-base-form > .v-select-header-form > .v-select-header-form-arrow').click();
  await page.getByText('AUTOMATIZADO').click();
  await page.getByText('Campos adicionales(Opcional)').click();
  await page.locator('[id="lgt_reg-item_v-tab:campos-adicionales_grilla-campos-adicionales:campo-adicional_v-input:texto"]').click();
  await page.locator('[id="lgt_reg-item_v-tab:campos-adicionales_grilla-campos-adicionales:campo-adicional_v-input:texto"]').fill('nueco combo desde auto');
  await page.locator('[id="lgt_reg-item_v-tab:campos-adicionales_grilla-campos-adicionales:campo-adicional_v-input:fecha"]').click();
  await page.getByRole('button', { name: 'jueves, 16 de abr de' }).click();
  await page.locator('div').filter({ hasText: /^crt$/ }).nth(2).click();
  await page.locator('div').filter({ hasText: /^crt$/ }).nth(4).click();
  await page.locator('.grilla-campos-adicionales').click();
  await page.locator('.grilla-campos-adicionales').click();
  await page.locator('[id="lgt_reg-item_v-tab:campos-adicionales_grilla-campos-adicionales:campo-adicional_v-input:numerico"]').click();
  await page.locator('[id="lgt_reg-item_v-tab:campos-adicionales_grilla-campos-adicionales:campo-adicional_v-input:numerico"]').fill('122121');
  await page.getByRole('button', { name: 'Crear combo' }).click();
  await page.getByRole('button', { name: 'Ir a lista de ítems' }).click();

  //combo con items equivalentea estrcictos

  await page.locator('[id="lgt_cmp-items_cmp-datos-items.cmp-option-button:crear"]').click();
  await page.getByText('CNuevo combo').click();
  await page.getByRole('textbox', { name: 'Ej. Gaseosa Kola R (500ml)' }).click();
  await page.getByRole('textbox', { name: 'Ej. Gaseosa Kola R (500ml)' }).fill('combo con equivalentes estrictos');
  await page.getByRole('textbox', { name: 'Monto final' }).first().click();
  await page.getByRole('textbox', { name: 'Monto final' }).first().fill('1414');
  await page.getByRole('textbox', { name: 'Monto final' }).nth(1).click();
  await page.getByRole('textbox', { name: 'Monto final' }).first().click();
  await page.getByRole('textbox', { name: 'Monto final' }).first().fill('14');
  await page.getByRole('textbox', { name: 'Monto final' }).nth(1).click();
  await page.getByRole('textbox', { name: 'Monto final' }).nth(1).fill('14');
  await page.locator('[id="lgt_cmp-registro-item_cmp-body-item_cmp-tabs-item.v-tabs:tabs-1"]').nth(1).click();
  await page.getByRole('textbox', { name: 'Buscar nombre del producto, c' }).click();
  await page.getByRole('textbox', { name: 'Buscar nombre del producto, c' }).click();
  await page.getByRole('textbox', { name: 'Buscar nombre del producto, c' }).fill('101010');
  await page.getByText('Peproducto101010item equivalente estricto gravado(Con Equivalencias)0 un').click();
  await page.getByText('item equivalente estricto gravadoFactor Multiplicador:1S/').click();
  await page.getByRole('textbox', { name: 'Buscar nombre del producto, c' }).click();
  await page.getByText('Peproducto101010item equivalente estricto gravado(Con Equivalencias)0 un').click();
  await page.getByText('Equivalente X2Factor').click();
  await page.getByRole('textbox', { name: 'Buscar nombre del producto, c' }).click();
  await page.getByText('item equivalente estricto').first().click();
  await page.getByText('Equivalencia X6Factor').click();
  await page.locator('div').filter({ hasText: /^Opciones avanzadas \(opcional\)$/ }).click();
  await page.locator('[id="lgt_cmp-registro-item_cmp-body-item_cmp-tabs-item.v-tabs:tabs-1"]').nth(2).click();
  await page.locator('div').filter({ hasText: /^Ninguna$/ }).nth(2).click();
  await page.locator('div').filter({ hasText: /^AUTO-TEST$/ }).nth(2).click();
  await page.locator('div').filter({ hasText: /^Ninguna$/ }).nth(2).click();
  await page.locator('div').filter({ hasText: /^AUTOMATIZADO$/ }).nth(2).click();
  await page.locator('[id="lgt_cmp-registro-item_cmp-body-item_cmp-tabs-item.v-tabs:tabs-3"]').nth(3).click();
  await page.locator('[id="lgt_cmp-registro-item_cmp-body-item_cmp-tabs-item.v-tabs:tabs-5"]').nth(4).click();
  await page.getByRole('button', { name: 'Crear combo' }).click();
  await page.getByRole('button', { name: 'Ir a lista de ítems' }).click();
  await page.locator('.flex-row-align-items-center-justify-content-center > .cmp-dropdown > .cmp-dropdown-toggle').first().click();
  await page.locator('[id="lgt_movimientos_cmp-grid-options:opciones_movimiento_cmp-dropdown:options-li:ver-item"]').click();
  await page.getByText('Bitácora').click();
  await page.getByRole('button', { name: 'Atrás' }).click();

  //Creacion de combo con items equivalentes flexibles

  await page.locator('[id="lgt_cmp-items_cmp-datos-items.cmp-option-button:crear"]').click();
  await page.getByText('CNuevo combo').click();
  await page.getByRole('textbox', { name: 'Ej. Gaseosa Kola R (500ml)' }).click();
  await page.getByRole('textbox', { name: 'Ej. Gaseosa Kola R (500ml)' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Ej. Gaseosa Kola R (500ml)' }).fill('C');
  await page.getByRole('textbox', { name: 'Ej. Gaseosa Kola R (500ml)' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Ej. Gaseosa Kola R (500ml)' }).fill('Combo con item equivalente flexible');
  await page.getByRole('textbox', { name: 'Monto final' }).first().click();
  await page.getByRole('textbox', { name: 'Monto final' }).first().fill('11');
  await page.getByRole('textbox', { name: 'Monto final' }).nth(1).click();
  await page.getByRole('textbox', { name: 'Monto final' }).nth(1).fill('11');
  await page.locator('[id="lgt_cmp-registro-item_cmp-body-item_cmp-tabs-item.v-tabs:tabs-1"]').nth(1).click();
  await page.getByRole('textbox', { name: 'Buscar nombre del producto, c' }).click();
  await page.getByRole('textbox', { name: 'Buscar nombre del producto, c' }).fill('202020');
  await page.getByText('Peproducto202020item equivalente flexible exonerado(Con Equivalencias)0 un').click();
  await page.getByText('item equivalente flexible exoneradoFactor Multiplicador:1S/').click();
  await page.getByRole('textbox', { name: 'Buscar nombre del producto, c' }).click();
  await page.getByText('Peproducto202020item equivalente flexible exonerado(Con Equivalencias)0 un').click();
  await page.getByText('Equivalente X2Factor').click();
  await page.getByRole('textbox', { name: 'Buscar nombre del producto, c' }).click();
  await page.getByText('Peproducto202020item').click();
  await page.getByText('Equivalencia X6Factor').click();
  await page.locator('div').filter({ hasText: /^Opciones avanzadas \(opcional\)$/ }).click();
  await page.locator('[id="lgt_cmp-registro-item_cmp-body-item_cmp-tabs-item.v-tabs:tabs-1"]').nth(2).click();
  await page.locator('div').filter({ hasText: /^Ninguna$/ }).nth(2).click();
  await page.locator('div').filter({ hasText: /^AUTO-TEST$/ }).nth(2).click();
  await page.locator('div:nth-child(2) > .form-control > .v-select > .v-select-form > .v-select-base > .v-select-base-header > .v-select-header-base-form > .v-select-header-form > .v-select-header-form-arrow').click();
  await page.getByText('AUTOMATIZADO').click();
  await page.getByRole('button', { name: 'Crear combo' }).click();
  await page.getByRole('button', { name: 'Ir a lista de ítems' }).click();
  await page.locator('.flex-row-align-items-center-justify-content-center > .cmp-dropdown > .cmp-dropdown-toggle').first().click();
  await page.locator('[id="lgt_movimientos_cmp-grid-options:opciones_movimiento_cmp-dropdown:options-li:ver-item"]').click();
  await page.locator('[id="lgt_ver-item_cmp-dashboard-item:tabs:cmp-tabs-options-item:opcion_div:bitacora"]').click();
  await page.getByRole('button', { name: 'Atrás' }).click();

  // Creacion de combos con selectores

  await page.locator('[id="lgt_cmp-items_cmp-datos-items.cmp-option-button:crear"]').click();
  await page.getByText('CNuevo combo').click();
  await page.getByRole('textbox', { name: 'Ej. Gaseosa Kola R (500ml)' }).click();
  await page.getByRole('textbox', { name: 'Ej. Gaseosa Kola R (500ml)' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Ej. Gaseosa Kola R (500ml)' }).fill('C');
  await page.getByRole('textbox', { name: 'Ej. Gaseosa Kola R (500ml)' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Ej. Gaseosa Kola R (500ml)' }).fill('Combo con item selectores estrictos');
  await page.getByRole('textbox', { name: 'Monto final' }).first().click();
  await page.getByRole('textbox', { name: 'Monto final' }).first().fill('222');
  await page.getByRole('textbox', { name: 'Monto final' }).nth(1).click();
  await page.getByRole('textbox', { name: 'Monto final' }).nth(1).fill('02');
  await page.getByRole('textbox', { name: 'Monto final' }).nth(1).click();
  await page.getByRole('textbox', { name: 'Monto final' }).nth(1).fill('22');
  await page.locator('[id="lgt_cmp-registro-item_cmp-body-item_cmp-tabs-item.v-tabs:tabs-1"]').nth(1).click();
  await page.getByRole('textbox', { name: 'Buscar nombre del producto, c' }).click();
  await page.getByRole('textbox', { name: 'Buscar nombre del producto, c' }).fill('454545');
  await page.getByText('Pproducto454545item selector gravado estricto con item manual0 un').click();
  await page.getByRole('textbox', { name: 'Buscar nombre del producto, c' }).click();
  await page.getByRole('textbox', { name: 'Buscar nombre del producto, c' }).press('ControlOrMeta+a');
  await page.getByRole('textbox', { name: 'Buscar nombre del producto, c' }).fill('545454');
  await page.getByRole('textbox', { name: 'Buscar nombre del producto, c' }).click();
  await page.getByRole('textbox', { name: 'Buscar nombre del producto, c' }).click();
  await page.getByRole('textbox', { name: 'Buscar nombre del producto, c' }).press('ControlOrMeta+a');
  await page.getByRole('textbox', { name: 'Buscar nombre del producto, c' }).fill('545454');
  await page.getByText('Pproducto545454item selector flexible0 un').click();
  await page.locator('div').filter({ hasText: /^Opciones avanzadas \(opcional\)$/ }).click();
  await page.locator('[id="lgt_cmp-registro-item_cmp-body-item_cmp-tabs-item.v-tabs:tabs-1"]').nth(2).click();
  await page.locator('div').filter({ hasText: /^Ninguna$/ }).nth(2).click();
  await page.locator('div').filter({ hasText: /^AUTO-TEST$/ }).nth(2).click();
  await page.locator('div').filter({ hasText: /^Ninguna$/ }).nth(2).click();
  await page.getByText('AUTOMATIZADO').click();
  await page.getByRole('button', { name: 'Crear combo' }).click();
  await page.getByRole('button', { name: 'Ir a lista de ítems' }).click();

  //Crear combo con variantes estrictos y fleixibles
  await page.locator('[id="lgt_cmp-items_cmp-datos-items.cmp-option-button:crear"]').click();
  await page.getByText('CNuevo combo').click();
  await page.getByRole('textbox', { name: 'Ej. Gaseosa Kola R (500ml)' }).click();
  await page.getByRole('textbox', { name: 'Ej. Gaseosa Kola R (500ml)' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Ej. Gaseosa Kola R (500ml)' }).fill('C');
  await page.getByRole('textbox', { name: 'Ej. Gaseosa Kola R (500ml)' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Ej. Gaseosa Kola R (500ml)' }).fill('Combo con item variantes');
  await page.locator('[id="lgt_cmp-registro-item_cmp-body-item_cmp-tabs-item.v-tabs:tabs-1"]').nth(1).click();
  await page.getByText('Información básica').click();
  await page.getByRole('textbox', { name: 'Monto final' }).first().click();
  await page.getByRole('textbox', { name: 'Monto final' }).first().fill('15');
  await page.getByRole('textbox', { name: 'Monto final' }).nth(1).click();
  await page.getByRole('textbox', { name: 'Monto final' }).nth(1).fill('15');
  await page.locator('[id="lgt_cmp-registro-item_cmp-body-item_cmp-tabs-item.v-tabs:tabs-1"]').nth(1).click();
  await page.getByRole('textbox', { name: 'Buscar nombre del producto, c' }).click();
  await page.getByRole('textbox', { name: 'Buscar nombre del producto, c' }).fill('131313');
  await page.getByText('Pvproducto131313item variante').click();
  await page.locator('.producto').first().click();
  await page.getByRole('textbox', { name: 'Buscar nombre del producto, c' }).click();
  await page.getByText('Pvproducto131313item variante').click();
  await page.locator('.v-modal-body > div:nth-child(2)').click();
  await page.getByRole('textbox', { name: 'Buscar nombre del producto, c' }).click();
  await page.getByText('Pvproducto').click();
  await page.locator('.v-modal-body > div:nth-child(3)').click();
  await page.getByRole('textbox', { name: 'Buscar nombre del producto, c' }).click();
  await page.getByRole('textbox', { name: 'Buscar nombre del producto, c' }).press('ControlOrMeta+a');
  await page.getByRole('textbox', { name: 'Buscar nombre del producto, c' }).fill('313131');
  await page.getByText('Pvproducto313131item con variante flexible(Con Variantes)0 un').click();
  await page.locator('.producto').first().click();
  await page.getByRole('textbox', { name: 'Buscar nombre del producto, c' }).click();
  await page.getByText('Pvproducto313131item con variante flexible(Con Variantes)0 un').click();
  await page.locator('.v-modal-body > div:nth-child(2)').click();
  await page.getByRole('textbox', { name: 'Buscar nombre del producto, c' }).click();
  await page.getByText('Pvproducto313131item con variante flexible(Con Variantes)0 un').click();
  await page.locator('.v-modal-body > div:nth-child(3)').click();
  await page.locator('div').filter({ hasText: /^Opciones avanzadas \(opcional\)$/ }).click();
  await page.getByText('Campos adicionales(Opcional)').click();
  await page.getByText('(Opcional)').first().click();
  await page.locator('div').filter({ hasText: /^Ninguna$/ }).nth(2).click();
  await page.locator('div').filter({ hasText: /^AUTO-TEST$/ }).nth(2).click();
  await page.locator('div').filter({ hasText: /^Ninguna$/ }).nth(2).click();
  await page.locator('div').filter({ hasText: /^AUTOMATIZADO$/ }).first().click();
  await page.getByRole('button', { name: 'Crear combo' }).click();
  await page.getByRole('button', { name: 'Ir a lista de ítems' }).click();
  await page.locator('.flex-row-align-items-center-justify-content-center > .cmp-dropdown > .cmp-dropdown-toggle').first().click();
  await page.locator('[id="lgt_movimientos_cmp-grid-options:opciones_movimiento_cmp-dropdown:options-li:ver-item"]').click();
  await page.getByText('VentasBitácora').click();
  await page.getByText('Bitácora').click();
  await page.getByRole('button', { name: 'Atrás' }).click();


  //combo con  variantes y equivalencias estrictas

  await page.locator('[id="lgt_cmp-items_cmp-datos-items.cmp-option-button:crear"]').click();
  await page.getByText('CNuevo combo').click();
  await page.getByRole('textbox', { name: 'Ej. Gaseosa Kola R (500ml)' }).click();
  await page.getByRole('textbox', { name: 'Ej. Gaseosa Kola R (500ml)' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Ej. Gaseosa Kola R (500ml)' }).fill('C');
  await page.getByRole('textbox', { name: 'Ej. Gaseosa Kola R (500ml)' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Ej. Gaseosa Kola R (500ml)' }).fill('Combo item variantes y equivalentes');
  await page.getByRole('textbox', { name: 'Monto final' }).first().click();
  await page.getByRole('textbox', { name: 'Monto final' }).first().fill('22');
  await page.getByRole('textbox', { name: 'Monto final' }).nth(1).click();
  await page.getByRole('textbox', { name: 'Monto final' }).nth(1).fill('12');
  await page.locator('[id="lgt_cmp-registro-item_cmp-body-item_cmp-tabs-item.v-tabs:tabs-1"]').nth(1).click();
  await page.getByRole('textbox', { name: 'Buscar nombre del producto, c' }).click();
  await page.getByRole('textbox', { name: 'Buscar nombre del producto, c' }).fill('131313');
  await page.getByText('Pvproducto131313item variante estricto gravado(Con Variantes)0 un').click();
  await page.locator('.producto').first().click();
  await page.getByRole('textbox', { name: 'Buscar nombre del producto, c' }).click();
  await page.getByText('Pvproducto131313item variante').click();
  await page.locator('.v-modal-body > div:nth-child(2)').click();
  await page.getByRole('textbox', { name: 'Buscar nombre del producto, c' }).click();
  await page.getByText('Pvproducto131313item variante estricto gravado(Con Variantes)0 un').click();
  await page.locator('.v-modal-body > div:nth-child(3)').click();
  await page.getByRole('textbox', { name: 'Buscar nombre del producto, c' }).click();
  await page.getByRole('textbox', { name: 'Buscar nombre del producto, c' }).press('ControlOrMeta+a');
  await page.getByRole('textbox', { name: 'Buscar nombre del producto, c' }).fill('101010');
  await page.getByText('Peproducto101010item equivalente estricto gravado(Con Equivalencias)0 un').click();
  await page.getByText('item equivalente estricto gravadoFactor Multiplicador:1S/').click();
  await page.getByRole('textbox', { name: 'Buscar nombre del producto, c' }).click();
  await page.getByText('Peproducto101010item equivalente estricto gravado(Con Equivalencias)0 un').click();
  await page.getByText('Equivalente X2Factor').click();
  await page.getByText('Opciones avanzadas (opcional)').click();
  await page.locator('[id="lgt_cmp-registro-item_cmp-body-item_cmp-tabs-item.v-tabs:tabs-1"]').nth(2).click();
  await page.locator('div').filter({ hasText: /^Ninguna$/ }).nth(2).click();
  await page.locator('div').filter({ hasText: /^AUTO-TEST$/ }).first().click();
  await page.locator('div').filter({ hasText: /^Ninguna$/ }).nth(2).click();
  await page.locator('div').filter({ hasText: /^AUTOMATIZADO$/ }).nth(2).click();
  await page.getByRole('button', { name: 'Crear combo' }).click();
  await page.getByRole('button', { name: 'Ir a lista de ítems' }).click();
  await page.locator('.flex-row-align-items-center-justify-content-center > .cmp-dropdown > .cmp-dropdown-toggle').first().click();
  await page.locator('[id="lgt_movimientos_cmp-grid-options:opciones_movimiento_cmp-dropdown:options-li:ver-item"]').click();
  await page.locator('[id="lgt_ver-item_cmp-dashboard-item:tabs:cmp-tabs-options-item:opcion_div:bitacora"]').click();
  await page.getByRole('button', { name: 'Atrás' }).click();

  //Combo exonerado con combo

  await page.locator('[id="lgt_cmp-items_cmp-datos-items.cmp-option-button:crear"]').click();
  await page.getByText('CNuevo combo').click();
  await page.getByRole('textbox', { name: 'Ej. Gaseosa Kola R (500ml)' }).click();
  await page.getByRole('textbox', { name: 'Ej. Gaseosa Kola R (500ml)' }).fill('combo sobre combo');
  await page.getByRole('textbox', { name: 'Monto final' }).first().click();
  await page.getByRole('textbox', { name: 'Monto final' }).first().fill('13');
  await page.getByRole('textbox', { name: 'Monto final' }).nth(1).click();
  await page.getByRole('textbox', { name: 'Monto final' }).nth(1).fill('13');
  await page.getByText('Añadir ítems').click();
  await page.getByRole('textbox', { name: 'Buscar nombre del producto, c' }).click();
  await page.getByRole('textbox', { name: 'Buscar nombre del producto, c' }).fill('222222');
  await page.getByRole('textbox', { name: 'Buscar nombre del producto, c' }).click();
  await page.getByRole('textbox', { name: 'Buscar nombre del producto, c' }).press('ControlOrMeta+a');
  await page.getByRole('textbox', { name: 'Buscar nombre del producto, c' }).click({
    modifiers: ['ControlOrMeta']
  });
  await page.getByRole('textbox', { name: 'Buscar nombre del producto, c' }).fill('22222');
  await page.getByRole('textbox', { name: 'Buscar nombre del producto, c' }).press('ControlOrMeta+c');
  await page.getByText('combo hijo exonegaro item').click();
  await page.getByRole('button', { name: 'Crear combo' }).click();
  await page.getByRole('button', { name: 'Ir a lista de ítems' }).click();
  await page.locator('.flex-row-align-items-center-justify-content-center > .cmp-dropdown > .cmp-dropdown-toggle').first().click();
  await page.locator('[id="lgt_movimientos_cmp-grid-options:opciones_movimiento_cmp-dropdown:options-li:ver-item"]').click();
  await page.getByText('Bitácora').click();
  await page.getByRole('button', { name: 'Atrás' }).click();


  //Creacion de receta con insumos


  await page.locator('[id="lgt_cmp-items_cmp-datos-items.cmp-option-button:crear"]').click();
  await page.getByText('RNueva receta').click();
  await page.getByRole('textbox', { name: 'Ej. Gaseosa Kola R (500ml)' }).click();
  await page.getByRole('textbox', { name: 'Ej. Gaseosa Kola R (500ml)' }).fill('nueva receta con items estrictos');
  await page.getByRole('textbox', { name: 'Monto final' }).first().click();
  await page.getByRole('textbox', { name: 'Monto final' }).first().fill('11');
  await page.getByRole('textbox', { name: 'Monto final' }).nth(1).click();
  await page.getByRole('textbox', { name: 'Monto final' }).nth(1).fill('3.5');
  await page.locator('[id="lgt_cmp-registro-item_cmp-body-item_cmp-tabs-item.v-tabs:tabs-1"]').nth(1).click();
  await page.getByRole('textbox', { name: 'Buscar nombre del producto, c' }).click();
  await page.getByRole('textbox', { name: 'Buscar nombre del producto, c' }).fill('444444');
  await page.getByText('Iinsumo444444Nuevo insumo0 un').click();
  await page.locator('body').press('ControlOrMeta+a');
  await page.locator('body').press('ControlOrMeta+a');
  await page.getByRole('textbox', { name: 'Buscar nombre del producto, c' }).click();
  await page.getByRole('textbox', { name: 'Buscar nombre del producto, c' }).press('ControlOrMeta+a');
  await page.getByRole('textbox', { name: 'Buscar nombre del producto, c' }).fill('');
  await page.getByRole('textbox', { name: 'Buscar nombre del producto, c' }).click();
  await page.getByRole('textbox', { name: 'Buscar nombre del producto, c' }).fill('464646');
  await page.getByText('Iinsumo464646Nuevo insumo test10 un').click();
  await page.getByRole('textbox', { name: 'Buscar nombre del producto, c' }).click();
  await page.getByRole('textbox', { name: 'Buscar nombre del producto, c' }).press('ControlOrMeta+a');
  await page.getByRole('textbox', { name: 'Buscar nombre del producto, c' }).fill('444666');
  await page.getByText('Ieinsumo444666nuevo insumo').click();
  await page.getByText('nuevo insumo con equivalencias estrictoFactor Multiplicador:1S/').click();
  await page.getByRole('textbox', { name: 'Buscar nombre del producto, c' }).click();
  await page.getByText('Ieinsumo444666nuevo insumo con equivalencias estricto(Con Equivalencias)0 un').click();
  await page.getByText('equivalenteX2 insumoFactor').click();
  await page.getByRole('textbox', { name: 'Buscar nombre del producto, c' }).click();
  await page.getByRole('textbox', { name: 'Buscar nombre del producto, c' }).press('ControlOrMeta+a');
  await page.getByRole('textbox', { name: 'Buscar nombre del producto, c' }).fill('666444');
  await page.locator('div').filter({ hasText: /^Iinsumo666444nuevo insumo flexible0 un$/ }).nth(2).click();
  await page.locator('div').filter({ hasText: /^Opciones avanzadas \(opcional\)$/ }).click();
  await page.locator('[id="lgt_cmp-registro-item_cmp-body-item_cmp-tabs-item.v-tabs:tabs-1"]').nth(2).click();
  await page.locator('div').filter({ hasText: /^Ninguna$/ }).nth(2).click();
  await page.locator('div').filter({ hasText: /^AUTO-TEST$/ }).nth(2).click();
  await page.locator('div').filter({ hasText: /^Ninguna$/ }).nth(2).click();
  await page.locator('div').filter({ hasText: /^AUTOMATIZADO$/ }).nth(2).click();
  await page.getByRole('button', { name: 'Crear receta' }).click();
  await page.getByRole('button', { name: 'Ir a lista de ítems' }).click();
  await page.locator('.flex-row-align-items-center-justify-content-center > .cmp-dropdown > .cmp-dropdown-toggle').first().click();
  await page.locator('[id="lgt_movimientos_cmp-grid-options:opciones_movimiento_cmp-dropdown:options-li:ver-item"]').click();
  await page.locator('[id="lgt_ver-item_cmp-dashboard-item:tabs:cmp-tabs-options-item:opcion_div:bitacora"]').click();
  await page.getByRole('button', { name: 'Atrás' }).click();


 // receta con items estrictos 

 await page.locator('[id="lgt_cmp-items_cmp-datos-items.cmp-option-button:crear"]').click();
 await page.getByText('RNueva receta').click();
 await page.getByRole('textbox', { name: 'Ej. Gaseosa Kola R (500ml)' }).click();
 await page.getByRole('textbox', { name: 'Ej. Gaseosa Kola R (500ml)' }).fill('receta con items esrictos');
 await page.getByRole('textbox', { name: 'Monto final' }).first().click();
 await page.getByRole('textbox', { name: 'Monto final' }).first().fill('10.10');
 await page.getByRole('textbox', { name: 'Monto final' }).nth(1).click();
 await page.getByRole('textbox', { name: 'Monto final' }).nth(1).fill('22');
 await page.locator('[id="lgt_cmp-registro-item_cmp-body-item_cmp-tabs-item.v-tabs:tabs-1"]').nth(1).click();
 await page.getByRole('textbox', { name: 'Buscar nombre del producto, c' }).click();
 await page.getByRole('textbox', { name: 'Buscar nombre del producto, c' }).fill('111111');
 await page.getByText('Pproducto111111Item para').click();
 await page.locator('body').press('ControlOrMeta+a');
 await page.getByRole('textbox', { name: 'Buscar nombre del producto, c' }).click({
    modifiers: ['ControlOrMeta']
  });
 await page.getByRole('textbox', { name: 'Buscar nombre del producto, c' }).press('ControlOrMeta+a');
 await page.getByRole('textbox', { name: 'Buscar nombre del producto, c' }).fill('101010');
 await page.getByText('Peproducto101010item').click();
 await page.getByText('item equivalente estricto gravadoFactor Multiplicador:1S/').click();
 await page.getByRole('textbox', { name: 'Buscar nombre del producto, c' }).click();
 await page.getByText('Peproducto101010item equivalente estricto gravado(Con Equivalencias)0 un').click();
 await page.getByText('Equivalente X2Factor').click();
 await page.getByRole('textbox', { name: 'Buscar nombre del producto, c' }).click();
 await page.getByRole('textbox', { name: 'Buscar nombre del producto, c' }).press('ControlOrMeta+a');
 await page.getByRole('textbox', { name: 'Buscar nombre del producto, c' }).fill('454545');
 await page.locator('div').filter({ hasText: /^Pproducto454545item selector gravado estricto con item manual0 un$/ }).nth(2).click();
 await page.locator('body').press('ControlOrMeta+a');
 await page.getByRole('textbox', { name: 'Buscar nombre del producto, c' }).click();
 await page.getByRole('textbox', { name: 'Buscar nombre del producto, c' }).fill('131313');
 await page.getByText('Pvproducto131313item variante').click();
 await page.locator('.producto').first().click();
 await page.locator('.producto').first().click();
 await page.locator('div').filter({ hasText: /^Opciones avanzadas \(opcional\)$/ }).click();
 await page.locator('[id="lgt_cmp-registro-item_cmp-body-item_cmp-tabs-item.v-tabs:tabs-1"]').nth(2).click();
 await page.locator('div').filter({ hasText: /^Ninguna$/ }).nth(2).click();
 await page.locator('div').filter({ hasText: /^AUTO-TEST$/ }).nth(2).click();
 await page.locator('div').filter({ hasText: /^Ninguna$/ }).nth(2).click();
 await page.getByText('AUTOMATIZADO').click();
 await page.getByRole('textbox', { name: 'Descripción del ítem' }).click();
 await page.getByRole('textbox', { name: 'Descripción del ítem' }).fill('nuevo auto con items estrictos()');
 await page.getByRole('textbox', { name: 'Descripción del ítem' }).press('ArrowLeft');
 await page.getByRole('textbox', { name: 'Descripción del ítem' }).fill('nuevo auto con items estrictos(variantes, equivalentes, selectores y items normales)');
 await page.getByRole('button', { name: 'Crear receta' }).click();
 await page.getByRole('button', { name: 'Ir a lista de ítems' }).click();
 await page.locator('.flex-row-align-items-center-justify-content-center > .cmp-dropdown > .cmp-dropdown-toggle').first().click();
 await page.locator('[id="lgt_movimientos_cmp-grid-options:opciones_movimiento_cmp-dropdown:options-li:ver-item"]').click();
 await page.locator('[id="lgt_ver-item_cmp-dashboard-item:tabs:cmp-tabs-options-item:opcion_div:bitacora"]').click();
 await page.getByRole('button', { name: 'Atrás' }).click();

 //receta con items flexibles
 
 await page.locator('[id="lgt_cmp-items_cmp-datos-items.cmp-option-button:crear"]').click();
 await page.getByText('RNueva receta').click();
 await page.getByRole('textbox', { name: 'Ej. Gaseosa Kola R (500ml)' }).click();
 await page.getByRole('textbox', { name: 'Ej. Gaseosa Kola R (500ml)' }).fill('receta con items flexibles');
 await page.getByRole('textbox', { name: 'Monto final' }).first().click();
 await page.getByRole('textbox', { name: 'Monto final' }).first().fill('11');
 await page.getByRole('textbox', { name: 'Monto final' }).nth(1).click();
 await page.getByRole('textbox', { name: 'Monto final' }).nth(1).fill('11');
 await page.locator('[id="lgt_cmp-registro-item_cmp-body-item_cmp-tabs-item.v-tabs:tabs-1"]').nth(1).click();
 await page.getByRole('textbox', { name: 'Buscar nombre del producto, c' }).click();
 await page.getByRole('textbox', { name: 'Buscar nombre del producto, c' }).fill('121212');
 await page.getByText('Pproducto121212item para combos gravado flexible0 un').click();
 await page.getByRole('textbox', { name: 'Buscar nombre del producto, c' }).click();
 await page.getByRole('textbox', { name: 'Buscar nombre del producto, c' }).press('ControlOrMeta+a');
 await page.getByRole('textbox', { name: 'Buscar nombre del producto, c' }).fill('313131');
 await page.getByText('Pvproducto313131item con').click();
 await page.locator('.producto').first().click();
 await page.getByRole('textbox', { name: 'Buscar nombre del producto, c' }).click();
 await page.getByRole('textbox', { name: 'Buscar nombre del producto, c' }).fill('');
 await page.getByRole('textbox', { name: 'Buscar nombre del producto, c' }).click();
 await page.getByRole('textbox', { name: 'Buscar nombre del producto, c' }).fill('202020');
 await page.getByText('Peproducto202020item').click();
 await page.getByText('Equivalente X2Factor').click();
 await page.getByRole('textbox', { name: 'Buscar nombre del producto, c' }).click();
 await page.getByText('Peproducto202020item equivalente flexible exonerado(Con Equivalencias)0 un').click();
 await page.getByText('Equivalencia X6Factor').click();
 await page.getByRole('textbox', { name: 'Buscar nombre del producto, c' }).click();
 await page.getByRole('textbox', { name: 'Buscar nombre del producto, c' }).fill('545454');
 await page.locator('div').filter({ hasText: /^Pproducto545454item selector flexible0 un$/ }).nth(2).click();
 await page.getByRole('textbox', { name: 'Buscar nombre del producto, c' }).click();
 await page.getByRole('textbox', { name: 'Buscar nombre del producto, c' }).click();
 await page.getByRole('textbox', { name: 'Buscar nombre del producto, c' }).fill('666444');
 await page.getByText('Iinsumo666444nuevo insumo flexible0 un').click();
 await page.locator('div').filter({ hasText: /^Opciones avanzadas \(opcional\)$/ }).click();
 await page.getByText('Información adicional').click();
 await page.locator('div').filter({ hasText: /^Ninguna$/ }).nth(2).click();
 await page.locator('div').filter({ hasText: /^AUTO-TEST$/ }).first().click();
 await page.locator('div').filter({ hasText: /^Ninguna$/ }).nth(2).click();
 await page.locator('div').filter({ hasText: /^AUTOMATIZADO$/ }).nth(2).click();
 await page.getByRole('button', { name: 'Crear receta' }).click();
 await page.getByText('Información básica').click();
 await page.getByRole('textbox', { name: 'Ej. Gaseosa Kola R (500ml)' }).click();
 await page.getByRole('textbox', { name: 'Ej. Gaseosa Kola R (500ml)' }).fill('receta con items flexibles test-auto');
 await page.getByRole('button', { name: 'Crear receta' }).click();
 await page.getByRole('button', { name: 'Ir a lista de ítems' }).click();
 await page.locator('.flex-row-align-items-center-justify-content-center > .cmp-dropdown > .cmp-dropdown-toggle').first().click();
 await page.getByText('Visualiza la información de').click();
 await page.getByText('Bitácora').click();
 await page.getByText('VentasBitácora').click();
 await page.getByText('Ventas', { exact: true }).click();
 await page.getByRole('button', { name: 'Atrás' }).click();

  // Creacion de lista con items estrictos

  await page.locator('[id="lgt_cmp-items_cmp-datos-items.cmp-option-button:crear"]').click();
  await page.getByText('LNueva lista').click();
  await page.locator('[id="cmn_cmp-overload:loading"]').click();
  await page.getByRole('textbox', { name: 'Ej. Lista de útiles primaria' }).click();
  await page.getByRole('textbox', { name: 'Ej. Lista de útiles primaria' }).fill('ñista de items estrictos');
  await page.getByRole('textbox', { name: 'Ej. Lista de útiles primaria' }).click();
  await page.getByRole('textbox', { name: 'Ej. Lista de útiles primaria' }).fill('lista de items estrictos');

  await page.getByRole('textbox', { name: 'Buscar nombre del producto, c' }).click();
  await page.getByRole('textbox', { name: 'Buscar nombre del producto, c' }).fill('111111');
  await page.getByText('Pproducto111111Item para combos estricto gravadoS/').click();
  await page.getByRole('textbox', { name: 'Buscar nombre del producto, c' }).click();
  await page.getByRole('textbox', { name: 'Buscar nombre del producto, c' }).press('ControlOrMeta+a');
  await page.getByRole('textbox', { name: 'Buscar nombre del producto, c' }).fill('131313');
  await page.getByText('Pvproducto131313item variante').click();
  await page.locator('.producto').first().click();
  await page.getByRole('textbox', { name: 'Buscar nombre del producto, c' }).click();
  await page.getByRole('textbox', { name: 'Buscar nombre del producto, c' }).press('ControlOrMeta+CapsLock');
  await page.getByRole('textbox', { name: 'Buscar nombre del producto, c' }).press('ControlOrMeta+A');
  await page.getByRole('textbox', { name: 'Buscar nombre del producto, c' }).fill('101010');
  await page.getByText('Peproducto101010item').click();
  await page.getByText('item equivalente estricto gravadoFactor Multiplicador:1S/').click();
  await page.getByRole('textbox', { name: 'Buscar nombre del producto, c' }).click();
  await page.getByRole('textbox', { name: 'Buscar nombre del producto, c' }).press('ControlOrMeta+A');
  await page.getByRole('textbox', { name: 'Buscar nombre del producto, c' }).fill('454545');
  await page.locator('div').filter({ hasText: /^Pproducto454545item selector gravado estricto con item manualS\/ 10\.00$/ }).nth(4).click();
  await page.getByRole('button', { name: 'Crear lista' }).click();
  await page.getByRole('button', { name: 'Ir a lista de ítems' }).click();

  //Creacion de lista con items flexibles
  
  await page.locator('[id="lgt_cmp-items_cmp-datos-items.cmp-option-button:crear"]').click();
  await page.getByText('LNueva lista').click();
  await page.locator('[id="cmn_cmp-overload:loading"]').click();
  await page.getByRole('textbox', { name: 'Ej. Lista de útiles primaria' }).click();
  await page.getByRole('textbox', { name: 'Ej. Lista de útiles primaria' }).fill('lista de items flexibles');
  await page.getByRole('textbox', { name: 'Ej. Lista de útiles primaria' }).click();
  await page.getByRole('textbox', { name: 'Ej. Lista de útiles primaria' }).fill('lista de items flexibles');

  await page.getByRole('textbox', { name: 'Buscar nombre del producto, c' }).click();
  await page.getByRole('textbox', { name: 'Buscar nombre del producto, c' }).fill('121212');
  await page.getByText('Pproducto121212item para combos gravado flexibleS/').click();
  await page.locator('body').press('ControlOrMeta+a');
  await page.getByRole('textbox', { name: 'Buscar nombre del producto, c' }).click();
  await page.getByRole('textbox', { name: 'Buscar nombre del producto, c' }).press('ControlOrMeta+a');
  await page.getByRole('textbox', { name: 'Buscar nombre del producto, c' }).fill('313131');
  await page.getByText('Pvproducto313131item con variante flexible(Con Variantes)S/').click();
  await page.getByText('Variante 1 flexibleMarca: AppleRAM: 32 GBMemoria: 500 GBVariante 2').click();
  await page.getByRole('textbox', { name: 'Buscar nombre del producto, c' }).click();
  await page.getByRole('textbox', { name: 'Buscar nombre del producto, c' }).fill('101010');
  await page.getByText('Peproducto101010item equivalente estricto gravado(Con Equivalencias)S/').click();
  await page.getByText('item equivalente estricto gravadoFactor Multiplicador:1S/').click();
  await page.getByRole('button', { name: 'Crear lista' }).click();
  await page.getByRole('button', { name: 'Ir a lista de ítems' }).click();
  await page.locator('.v-icon-base > .icon').first().click();
  await page.locator('[id="lgt_movimientos_cmp-grid-options:opciones_movimiento_cmp-dropdown:options-li:ver-item"]').click();
  await page.locator('div').filter({ hasText: /^Ver listado$/ }).click();
  await page.locator('.v-modal > div').first().click();
  await page.getByRole('button', { name: 'Atrás' }).click();

});
