import {expect, test} from '@playwright/test';

test('test', async ({page}) => {

    //Primer caso
    await page.goto('https://erpperu2-crt.smartclic.pe/auth/login');
    await page.getByText('Ventas y compras').click();
    await page.getByText('Ver cajas').click();
    await page.getByRole('button', {name: 'Continuar vendiendo'}).click();
    await page.locator('div').filter({hasText: /^BOLETA$/}).nth(1).click();
    await page.locator('[id="pv_punto-venta_cmp-venta-pedido_cmp-pedido-header_v-select:tipo-comprobante_v-option:opcion-3007"]').click();
    await page.getByRole('textbox', {name: 'Buscar por nombre, razón'}).click();
    await page.getByRole('textbox', {name: 'Buscar por nombre, razón'}).fill('76975258');
    await page.getByText('DNIDoc. Nacional de Identidad7697525899999999JHUNIOR BRAYAN GUTIERREZ MAMANIav-').click();
    await page.getByRole('textbox', {name: 'Escanea o busca por nombre, c'}).click();
    await page.getByRole('textbox', {name: 'Escanea o busca por nombre, c'}).fill('151515');
    await page.getByText('item gravado sin control').click();
    await expect(page.getByRole('main')).toContainText('Validez de la oferta');
    await page.locator('div').filter({hasText: /^0 días$/}).nth(1).click();
    await page.getByText('15 días').click();
    await expect(page.getByText('días').first()).toBeVisible();
    await page.locator('.collapse-icon').click();
    await expect(page.getByRole('main')).toContainText('Total1 ítemsS/10.25');
    await page.getByRole('button', {name: 'PAGAR'}).click();
    await expect(page.locator('div').filter({hasText: /^Enviar por WhatsApp$/}).first()).toBeVisible();
    await page.locator('div').filter({hasText: /^Enviar por Email$/}).first().click();
    await page.locator('div').filter({hasText: /^Copiar Link$/}).first().click();
    await page.locator('div').filter({hasText: /^Descargar XML$/}).first().click();
    const downloadPromise = page.waitForEvent('download');
    await page.locator('div').filter({hasText: /^Descargar PDF$/}).first().click();
    const download = await downloadPromise;
    await expect(page.locator('div').filter({hasText: /^Descargar PDF$/}).first()).toBeVisible();
    await expect(page.getByRole('button', {name: 'Imprimir', exact: true})).toBeVisible();
    await expect(page.getByRole('button', {name: 'Imprimir Ticket'})).toBeVisible();
    await page.getByRole('button', {name: 'Nueva Venta'}).click();
    await page.locator('.icon').first().click();
    await page.getByText('Ventas y compras').click();
    await page.locator('div').filter({hasText: /^Búsqueda de comprobantes$/}).nth(1).click();
    await expect(page.locator('[id="single-spa-application:@sreasons/erp-mf-punto-venta"]')).toContainText('Búsqueda de comprobantes');
    await page.getByRole('button', {name: 'Ver filtros avanzados'}).click();
    await page.locator('.vector').first().click();
    await page.getByText('Cotización', {exact: true}).click();
    await page.locator('.vector').first().click();
    await page.getByRole('textbox', {name: 'Correlativo'}).click();
    await page.getByRole('textbox', {name: 'Correlativo'}).fill('1');
    await page.locator('[id="pv_comprobantes_cmp-grid-comprobantes_cmp-grid-comprobantes-body_cmp-grid-comprobantes-body-options_cmp-dropdown:3252372"]').click();
    await page.getByText('Bitácora').click();
    await expect(page.locator('body')).toContainText('Operacion Satisfactoria - ERP 2');
    await page.getByText('Operacion Satisfactoria - ERP').nth(1).click();
    await expect(page.locator('body')).toContainText('Archivo PDF Generado. - ERP 2');
    await expect(page.locator('body')).toContainText('Operacion Satisfactoria - ERP 2');
    await page.locator('.button-close').first().click();
    await page.locator('[id="pv_comprobantes_cmp-grid-comprobantes_cmp-grid-comprobantes-body_cmp-grid-comprobantes-body-options_cmp-dropdown:3252372"]').click();
    const page1Promise = page.waitForEvent('popup');
    await page.getByRole('link', {name: 'Ver comprobante'}).click();
    const page1 = await page1Promise;
    await expect(page1.locator('[id="single-spa-application:@sreasons/erp-mf-punto-venta"]')).toContainText('Cotización');
    await page1.getByRole('button', {name: 'Salir'}).click();
});